# This is a docker compose override file, for testing production builds with caching for CI environments
services:
  daemon:
    build:
      dockerfile: Dockerfile.daemon
      context: .
      target: prod
      cache_from:
        - type=local,src=/tmp/.buildx-cache-daemon
      # cache_to:
      #   - type=local,dest=/tmp/.buildx-cache-daemon,mode=max

  awards:
    build:
      dockerfile: Dockerfile.daemon
      context: .
      target: prod
      cache_from:
        - type=local,src=/tmp/.buildx-cache-daemon
      # cache_to:
      #   - type=local,dest=/tmp/.buildx-cache-daemon,mode=max

  web:
    build:
      dockerfile: Dockerfile.web
      context: .
      target: prod
      cache_from:
        - type=local,src=/tmp/.buildx-cache-web
      # cache_to:
      #   - type=local,dest=/tmp/.buildx-cache-web,mode=max

  heatmaps:
    build:
      dockerfile: Dockerfile.web
      context: .
      target: prod
      cache_from:
        - type=local,src=/tmp/.buildx-cache-web
      # cache_to:
      #   - type=local,dest=/tmp/.buildx-cache-web,mode=max
