# This is a docker compose override file, for development builds with caching for CI environments
services:
  daemon:
    build:
      cache_from:
        - type=local,src=/tmp/.buildx-cache-daemon
      cache_to:
        - type=local,dest=/tmp/.buildx-cache-daemon,mode=max

  awards:
    build:
      cache_from:
        - type=local,src=/tmp/.buildx-cache-daemon
      cache_to:
        - type=local,dest=/tmp/.buildx-cache-daemon,mode=max

  web:
    build:
      cache_from:
        - type=local,src=/tmp/.buildx-cache-web
      cache_to:
        - type=local,dest=/tmp/.buildx-cache-web,mode=max

  heatmaps:
    build:
      cache_from:
        - type=local,src=/tmp/.buildx-cache-web
      cache_to:
        - type=local,dest=/tmp/.buildx-cache-web,mode=max
